import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useState } from "react";
import Header from "~/components/Header";
import NoteCard from "~/components/NoteCard";
import NoteEditor from "~/components/NoteEditor";
import { api,type RouterOutputs } from "~/utils/api";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Note app</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header />
                <Content />
            </main>
        </>
    );
};

type Topic = RouterOutputs["topic"]["getAll"][0];

function Content() {
    const { data: session } = useSession();
    const [selectedTopic, setSelectedTopic] = useState<Topic | null>(null);

    const { data: topics, refetch: refetchTopic } = api.topic.getAll
        .useQuery(undefined, {
            onSuccess: (data) => {
                setSelectedTopic(selectedTopic ?? data[0] ?? null);
            },
        });
    const createTopic = api.topic.create.useMutation({
        onSuccess: () => {
            void refetchTopic();
        },
    });

    const { data: notes, refetch: refetchNote } = api.note.getAll.useQuery({
        topicId: selectedTopic?.id ?? "",
    }, {
        enabled: session?.user?.id != undefined && selectedTopic != null,
    });

    const createNote = api.note.create.useMutation({
        onSuccess: () => {
            void refetchNote();
        },
    });

    const deleteNote = api.note.delete.useMutation({
        onSuccess: () => {
            void refetchNote();
        },
    });
    return (
        <section className="m-5 grid grid-cols-3 gap-2">
            <article className="px-2">
                <ul className="menu">
                    {topics?.map((topic) => (
                        <li key={topic.id}>
                            <a
                                href="#"
                                onClick={(evt) => {
                                    evt.preventDefault();
                                    setSelectedTopic(topic);
                                }}
                            >
                                {topic.title}
                            </a>
                        </li>
                    ))}
                </ul>
                <div className="divider">
                </div>
                <input
                    onKeyDown={(e) => {
                        if (e.key === "Enter") {
                            createTopic.mutate({
                                title: e.currentTarget.value,
                            });
                            e.currentTarget.value = "";
                        }
                    }}
                    type="text"
                    placeholder="Add a topic"
                    className="input input-bordered input-sm w-full"
                />
            </article>
            <article className="col-span-2">
                <ul>
                    {notes?.map((note) => (
                        <li key={note.id}>
                            <NoteCard
                                note={note}
                                onDelete={() =>
                                    void deleteNote.mutate({
                                        id: note.id,
                                    })}
                            />
                        </li>
                    ))}
                </ul>

                <NoteEditor
                    onSave={({ title, content }) => {
                        void createNote.mutate({
                            title,
                            content,
                            topicId: selectedTopic?.id ?? "",
                        });
                    }}
                />
            </article>
        </section>
    );
}

export default Home;
